import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster"
import { Analytics } from '@vercel/analytics/next';

import {
  ClerkProvider,
  
} from '@clerk/nextjs'



export const metadata: Metadata = {
  title: "Truck Sales",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>

  
    <html lang="en">
      <body
     
      >
      
        {children}
        <Analytics/>
        <Toaster/>
      
      
      </body>
    </html>
    </ClerkProvider>
  );
}
